# Generated by Django 4.2.7 on 2025-06-22 04:46

import datetime
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='カテゴリ名')),
                ('category_type', models.CharField(choices=[('income', '収入'), ('expense', '支出')], max_length=10, verbose_name='種別')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='表示色')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': 'カテゴリ',
                'verbose_name_plural': 'カテゴリ',
                'ordering': ['category_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='YearlyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True, verbose_name='年')),
                ('savings_goal', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='貯蓄目標額')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': '年間目標',
                'verbose_name_plural': '年間目標',
            },
        ),
        migrations.CreateModel(
            name='BudgetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='日付')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='金額')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.category', verbose_name='カテゴリ')),
            ],
            options={
                'verbose_name': '家計簿エントリ',
                'verbose_name_plural': '家計簿エントリ',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='年')),
                ('month', models.IntegerField(verbose_name='月')),
                ('budget_amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='予算額')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.category', verbose_name='カテゴリ')),
            ],
            options={
                'verbose_name': '月別予算',
                'verbose_name_plural': '月別予算',
                'unique_together': {('year', 'month', 'category')},
            },
        ),
    ]
